services:
    host-a:
        image: edugarrick/centos-8-python
        container_name: host-a
        tty: true       
        cap_add:
                - ALL
        privileged: true
        network_mode: "host"    
    host-b:
        image: edugarrick/centos-8-python
        container_name: host-b
        tty: true           
        cap_add:
                - ALL
        privileged: true
        network_mode: "host"     
    attacker:
        image: edugarrick/kali-desktop
        container_name: attacker
        tty: true
        network_mode: "host"
        cap_add:
            - ALL
        privileged: true
        volumes:
            - ./src:/src


